name: Build ldap utils

on:
  pull_request:
    branches:
      - master
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Golang
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'
        - name: Build ldap utils
          run: |
            go build -o ldaputils
        - name: Login to DockerHub and push image
          run: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t firstfloor/ldaputils:latest .
            docker push firstfloor/ldaputils:latest
        